version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aki_finder_api_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "bundle exec rails db:create db:migrate && rails s -b 0.0.0.0"
    volumes:
      - .:/aki_finder_api
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
