version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aki_finder_api_development
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: rails
      DATABASE_PASSWORD: password
      DATABASE_NAME: aki_finder_api_development
      RAILS_ENV: development

volumes:
  db_data:
